version: "3.8"
services:
  piletas-frontend-production:
    container_name: piletas-frontend-production
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - "5173:5173"
